// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MomCare.Data;

#nullable disable

namespace MomCare.Infrastructure.PostgreSqlMigrations
{
    [DbContext(typeof(MomCareContext))]
    [Migration("20260602024500_AddCustomerSessionFeedbackTags")]
    public partial class AddCustomerSessionFeedbackTags
    {
    }
}
