// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MomCare.Data;

#nullable disable

namespace MomCare.Infrastructure.PostgreSqlMigrations
{
    [DbContext(typeof(MomCareContext))]
    [Migration("20260604090000_AddHealthCheckInContextData")]
    partial class AddHealthCheckInContextData
    {
    }
}
